### ISSUE TITLE
'ENVFILE' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by saikiran-dev** [nobejs/nobejs#24]
Facing issue while running the first migration
 
 https://stackoverflow.com/questions/72457711/envfile-is-not-recognized-as-an-internal-or-external-command-operable-program?noredirect=1#comment128000781_72457711
  @rjvim @ShubhamJoshi-1994

**Comment by rjvim** [comment]
@saikiran-dev Just need one more piece of information.

Run you running in windows?

**Comment by saikiran-dev** [comment]
Correct!

**Comment by rjvim** [comment]
@saikiran-dev Windows doesn't recognize inline ENV variables, so one way to do it is:

```
"win:serve": "SET ENVFILE=.env && nodemon server.js"
```

or

```
"win:serve": "SET ENVFILE=.env&& nodemon server.js"
```

Add a command like the above to your package.json file and try it.

**Comment by rjvim** [comment]
@saikiran-dev Was it helpful

**Comment by saikiran-dev** [comment]
No luck @rjvim , I tried both. Issue is while creating the migration. When I run `yarn db:migration create_photos_table` I'm seeing the issue.

![image](https://user-images.githubusercontent.com/54679219/171684161-8a61f0a5-6970-40b4-898d-2ff4351688c7.png)

**Comment by rjvim** [comment]
@saikiran-dev 

```
SET ENVFILE=.env&&knex migrate:make create_photos_table
```

```
SET ENVFILE=.env && knex migrate:make create_photos_table
```

Do one of the above work?

----

The issue you are facing is this: https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows

This is a common windows issue, some have written packages like: https://www.npmjs.com/package/win-node-env 

It also depends on if you are using Powershell or CMD etc.,

**Comment by saikiran-dev** [comment]
It is working in CMD and git bash @rjvim . Command is

`"win:migration": "SET ENVFILE=.env && knex migrate:make"`

**Comment by rjvim** [comment]
@saikiran-dev 👍
